name: Build/Update Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
env:
  PROJECT_ID: dt-patrick-project-dev
  COMPOSER_BUCKET: europe-west2-pipeline-compo-326f64fd-bucket

jobs:
  load-dbt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }} # can be base64 encoded or plain text
        registry: gcr.io
        project_id: ${{ env.PROJECT_ID }}
        image_name: dbt-runner
        image_tag: latest